<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Authors>GroupDocs</Authors>
    <Company>GroupDocs</Company>
    <Description>Examples of using GroupDocs.Metadata.Cloud SDK</Description>
    <Copyright>Aspose Pty Ltd</Copyright>
    <PackageProjectUrl>https://products.groupdocs.cloud/metadata/net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/groupdocs-metadata-cloud/groupdocs-metadata-cloud-dotnet-samples</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GroupDocs.Metadata-Cloud" Version="26.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>